version: '3.8'
services:
  server:
    container_name: rest-server
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    container_name: rest-db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '9906:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    hostname: database
    env_file: .env

volumes:
  postgres:
